"""Keep literal message text distinct from Nemotron's reasoning control tokens.

The opt-in template still renders exactly the same text. A shadow rendering
locates caller-content markers; only their token IDs are replaced with normal
BPE pieces. Framing generated by the template and actual reasoning prefixes
remain control tokens. No caller text or decoded prompt is rewritten.
"""

import copy
import json
import re
import uuid
from functools import lru_cache

TEMPLATE_OPT_IN = "phala-nemotron-literal-message-tokens-v1"
MARKERS = ("<think>", "</think>", "<tool_call>", "</tool_call>")


@lru_cache(maxsize=4)
def _literal_marker_pieces(tokenizer):
    from tokenizers import Tokenizer

    config = json.loads(tokenizer.backend_tokenizer.to_str())
    marker_ids = {
        token["content"]: token["id"]
        for token in config["added_tokens"]
        if token["content"] in MARKERS
    }
    if not set(MARKERS[:2]).issubset(marker_ids):
        raise ValueError("Nemotron literal-token template requires its added markers")
    config["added_tokens"] = [
        token
        for token in config["added_tokens"]
        if token["id"] not in marker_ids.values()
    ]
    ordinary = Tokenizer.from_str(json.dumps(config))
    pieces = {
        marker: ordinary.encode(marker, add_special_tokens=False).ids
        for marker in marker_ids
    }
    for marker, ids in pieces.items():
        if not ids or set(ids).intersection(marker_ids.values()):
            raise ValueError("Nemotron literal marker did not split into normal BPE")
        if tokenizer.decode(ids, skip_special_tokens=False) != marker:
            raise ValueError("Nemotron literal BPE changed decoded text")
    return marker_ids, pieces


def _contains_literals(value):
    if isinstance(value, str):
        return any(marker in value for marker in MARKERS)
    if isinstance(value, dict):
        return any(
            _contains_literals(k) or _contains_literals(v) for k, v in value.items()
        )
    if isinstance(value, (list, tuple)):
        return any(_contains_literals(item) for item in value)
    return False


def _replace_literals(value, placeholders):
    if isinstance(value, str):
        for marker, placeholder in placeholders.items():
            value = value.replace(marker, placeholder)
        return value
    if isinstance(value, dict):
        return {
            _replace_literals(k, placeholders): _replace_literals(v, placeholders)
            for k, v in value.items()
        }
    if isinstance(value, list):
        return [_replace_literals(item, placeholders) for item in value]
    if isinstance(value, tuple):
        return tuple(_replace_literals(item, placeholders) for item in value)
    return value


def _protect_content(message, placeholders):
    content = message.get("content")
    if not isinstance(content, str):
        return False
    prefix = ""
    # Preserve the template's legacy combined-reasoning input contract. With a
    # separate reasoning field, content is final-answer data instead.
    if (
        message.get("role") == "assistant"
        and not message.get("reasoning_content")
        and content.lstrip().startswith(MARKERS[0])
    ):
        end = content.find(MARKERS[1])
        if end < 0:
            return False
        end += len(MARKERS[1])
        prefix, content = content[:end], content[end:]
    protected = content
    for marker, placeholder in placeholders.items():
        protected = protected.replace(marker, placeholder)
    if protected == content:
        return False
    message["content"] = prefix + protected
    return True


def encode_nemotron_message_literals(
    tokenizer,
    messages,
    rendered_prompt,
    prompt_ids,
    render_messages,
    *,
    template_data=None,
):
    """Return original IDs except for literal added markers in message content.

    The caller owns model/continuation routing. Only the explicit opt-in
    template is supported; custom templates and nonliteral fast paths retain
    their original encoding. No request, tokenizer or model artifact is mutated.
    """
    template = getattr(tokenizer, "chat_template", None)
    if not isinstance(template, str) or TEMPLATE_OPT_IN not in template:
        return prompt_ids
    protected_fields = ("content", "reasoning_content", "tool_calls")
    caller_data = [
        {k: message.get(k) for k in protected_fields} for message in messages
    ]
    template_values = {
        k: (template_data or {}).get(k) for k in ("response_format", "tools")
    }
    if not _contains_literals((caller_data, template_values)):
        return prompt_ids

    marker_ids, pieces = _literal_marker_pieces(tokenizer)
    nonce = uuid.uuid4().hex
    while nonce in rendered_prompt:
        nonce = uuid.uuid4().hex
    placeholders = {
        marker: f"PHALA_LITERAL_{nonce}_{i}_END" for i, marker in enumerate(marker_ids)
    }
    shadow_messages = copy.deepcopy(messages)
    changed = [_protect_content(message, placeholders) for message in shadow_messages]
    for message in shadow_messages:
        for field in protected_fields[1:]:
            if field in message:
                original = message[field]
                message[field] = _replace_literals(original, placeholders)
                changed.append(message[field] != original)
    shadow_template = copy.deepcopy(template_data)
    if shadow_template is not None:
        for key in template_values:
            if key in shadow_template:
                original = shadow_template[key]
                shadow_template[key] = _replace_literals(original, placeholders)
                changed.append(shadow_template[key] != original)
    if not any(changed):
        return prompt_ids
    shadow = (
        render_messages(shadow_messages)
        if shadow_template is None
        else render_messages(shadow_messages, shadow_template)
    )
    pattern = re.compile("|".join(re.escape(p) for p in placeholders.values()))
    reverse = {value: key for key, value in placeholders.items()}
    restored = []
    spans = {}
    cursor = 0
    length = 0
    for match in pattern.finditer(shadow):
        normal = shadow[cursor : match.start()]
        marker = reverse[match.group()]
        restored.extend((normal, marker))
        length += len(normal)
        spans[(length, length + len(marker))] = marker
        length += len(marker)
        cursor = match.end()
    restored.append(shadow[cursor:])
    if "".join(restored) != rendered_prompt:
        raise ValueError("Nemotron literal-token shadow changed template rendering")
    if not spans:
        return prompt_ids

    encoding = tokenizer.backend_tokenizer.encode(
        rendered_prompt, add_special_tokens=False
    )
    if encoding.ids != prompt_ids:
        raise ValueError("Nemotron literal-token offsets do not match prompt IDs")
    output = []
    found = set()
    for token_id, offset in zip(encoding.ids, encoding.offsets):
        offset = tuple(offset)
        marker = spans.get(offset)
        if marker is None:
            output.append(token_id)
            continue
        if token_id != marker_ids[marker]:
            raise ValueError("Nemotron literal span is not its expected added token")
        output.extend(pieces[marker])
        found.add(offset)
    if found != set(spans):
        raise ValueError("Nemotron literal-token offsets missed caller content")
    if tokenizer.decode(output, skip_special_tokens=False) != tokenizer.decode(
        prompt_ids, skip_special_tokens=False
    ):
        raise ValueError("Nemotron literal-token conversion changed decoded prompt")
    return output
